sudo: required
services: docker
language: bash

before_install:
  # Install docker 17.05.0 or later
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - sudo ./build.sh
